// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record.proto

package zqbrecord

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RecordAddStatus_Enum int32

const (
	// 失敗
	RecordAddStatus_failure RecordAddStatus_Enum = 0
	// 成功
	RecordAddStatus_success RecordAddStatus_Enum = 1
)

var RecordAddStatus_Enum_name = map[int32]string{
	0: "failure",
	1: "success",
}

var RecordAddStatus_Enum_value = map[string]int32{
	"failure": 0,
	"success": 1,
}

func (x RecordAddStatus_Enum) String() string {
	return proto.EnumName(RecordAddStatus_Enum_name, int32(x))
}

func (RecordAddStatus_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0, 0}
}

type OrderRevenueStatus_Enum int32

const (
	// 配對中
	OrderRevenueStatus_pair OrderRevenueStatus_Enum = 0
	// 成功(收到款)
	OrderRevenueStatus_success OrderRevenueStatus_Enum = 1
	// 搶單失敗
	OrderRevenueStatus_failure OrderRevenueStatus_Enum = 2
	// 配對成功-等待轉帳
	OrderRevenueStatus_hit OrderRevenueStatus_Enum = 3
	// 搶到單-沒收到款
	OrderRevenueStatus_unpaid OrderRevenueStatus_Enum = 4
	// 無人搶單
	OrderRevenueStatus_none OrderRevenueStatus_Enum = -1
)

var OrderRevenueStatus_Enum_name = map[int32]string{
	0:  "pair",
	1:  "success",
	2:  "failure",
	3:  "hit",
	4:  "unpaid",
	-1: "none",
}

var OrderRevenueStatus_Enum_value = map[string]int32{
	"pair":    0,
	"success": 1,
	"failure": 2,
	"hit":     3,
	"unpaid":  4,
	"none":    -1,
}

func (x OrderRevenueStatus_Enum) String() string {
	return proto.EnumName(OrderRevenueStatus_Enum_name, int32(x))
}

func (OrderRevenueStatus_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{3, 0}
}

// 收單建立狀態
type RecordAddStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordAddStatus) Reset()         { *m = RecordAddStatus{} }
func (m *RecordAddStatus) String() string { return proto.CompactTextString(m) }
func (*RecordAddStatus) ProtoMessage()    {}
func (*RecordAddStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{0}
}

func (m *RecordAddStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordAddStatus.Unmarshal(m, b)
}
func (m *RecordAddStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordAddStatus.Marshal(b, m, deterministic)
}
func (m *RecordAddStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordAddStatus.Merge(m, src)
}
func (m *RecordAddStatus) XXX_Size() int {
	return xxx_messageInfo_RecordAddStatus.Size(m)
}
func (m *RecordAddStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordAddStatus.DiscardUnknown(m)
}

var xxx_messageInfo_RecordAddStatus proto.InternalMessageInfo

// 收單
type RecordAddReq struct {
	// 類型id
	PaymentDtlId         int64    `protobuf:"varint,1,opt,name=payment_dtl_id,json=paymentDtlId,proto3" json:"payment_dtl_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordAddReq) Reset()         { *m = RecordAddReq{} }
func (m *RecordAddReq) String() string { return proto.CompactTextString(m) }
func (*RecordAddReq) ProtoMessage()    {}
func (*RecordAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{1}
}

func (m *RecordAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordAddReq.Unmarshal(m, b)
}
func (m *RecordAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordAddReq.Marshal(b, m, deterministic)
}
func (m *RecordAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordAddReq.Merge(m, src)
}
func (m *RecordAddReq) XXX_Size() int {
	return xxx_messageInfo_RecordAddReq.Size(m)
}
func (m *RecordAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordAddReq proto.InternalMessageInfo

func (m *RecordAddReq) GetPaymentDtlId() int64 {
	if m != nil {
		return m.PaymentDtlId
	}
	return 0
}

type RecordAddResp struct {
	// 單號
	RecordId             int64                `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Status               RecordAddStatus_Enum `protobuf:"varint,2,opt,name=status,proto3,enum=zqbrecord.RecordAddStatus_Enum" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RecordAddResp) Reset()         { *m = RecordAddResp{} }
func (m *RecordAddResp) String() string { return proto.CompactTextString(m) }
func (*RecordAddResp) ProtoMessage()    {}
func (*RecordAddResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{2}
}

func (m *RecordAddResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordAddResp.Unmarshal(m, b)
}
func (m *RecordAddResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordAddResp.Marshal(b, m, deterministic)
}
func (m *RecordAddResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordAddResp.Merge(m, src)
}
func (m *RecordAddResp) XXX_Size() int {
	return xxx_messageInfo_RecordAddResp.Size(m)
}
func (m *RecordAddResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordAddResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordAddResp proto.InternalMessageInfo

func (m *RecordAddResp) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *RecordAddResp) GetStatus() RecordAddStatus_Enum {
	if m != nil {
		return m.Status
	}
	return RecordAddStatus_failure
}

// 期數狀態
type OrderRevenueStatus struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRevenueStatus) Reset()         { *m = OrderRevenueStatus{} }
func (m *OrderRevenueStatus) String() string { return proto.CompactTextString(m) }
func (*OrderRevenueStatus) ProtoMessage()    {}
func (*OrderRevenueStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{3}
}

func (m *OrderRevenueStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRevenueStatus.Unmarshal(m, b)
}
func (m *OrderRevenueStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRevenueStatus.Marshal(b, m, deterministic)
}
func (m *OrderRevenueStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRevenueStatus.Merge(m, src)
}
func (m *OrderRevenueStatus) XXX_Size() int {
	return xxx_messageInfo_OrderRevenueStatus.Size(m)
}
func (m *OrderRevenueStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRevenueStatus.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRevenueStatus proto.InternalMessageInfo

// 期數狀態反查
type RecordGetStatusReq struct {
	// 單號
	RecordId             int64    `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordGetStatusReq) Reset()         { *m = RecordGetStatusReq{} }
func (m *RecordGetStatusReq) String() string { return proto.CompactTextString(m) }
func (*RecordGetStatusReq) ProtoMessage()    {}
func (*RecordGetStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{4}
}

func (m *RecordGetStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordGetStatusReq.Unmarshal(m, b)
}
func (m *RecordGetStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordGetStatusReq.Marshal(b, m, deterministic)
}
func (m *RecordGetStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordGetStatusReq.Merge(m, src)
}
func (m *RecordGetStatusReq) XXX_Size() int {
	return xxx_messageInfo_RecordGetStatusReq.Size(m)
}
func (m *RecordGetStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordGetStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordGetStatusReq proto.InternalMessageInfo

func (m *RecordGetStatusReq) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

type RecordGetStatusResp struct {
	// 單號
	RecordId             int64                   `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Status               OrderRevenueStatus_Enum `protobuf:"varint,2,opt,name=status,proto3,enum=zqbrecord.OrderRevenueStatus_Enum" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RecordGetStatusResp) Reset()         { *m = RecordGetStatusResp{} }
func (m *RecordGetStatusResp) String() string { return proto.CompactTextString(m) }
func (*RecordGetStatusResp) ProtoMessage()    {}
func (*RecordGetStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{5}
}

func (m *RecordGetStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordGetStatusResp.Unmarshal(m, b)
}
func (m *RecordGetStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordGetStatusResp.Marshal(b, m, deterministic)
}
func (m *RecordGetStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordGetStatusResp.Merge(m, src)
}
func (m *RecordGetStatusResp) XXX_Size() int {
	return xxx_messageInfo_RecordGetStatusResp.Size(m)
}
func (m *RecordGetStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordGetStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordGetStatusResp proto.InternalMessageInfo

func (m *RecordGetStatusResp) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

func (m *RecordGetStatusResp) GetStatus() OrderRevenueStatus_Enum {
	if m != nil {
		return m.Status
	}
	return OrderRevenueStatus_pair
}

// 取得QRCode
type RecordGetQRCodeReq struct {
	// 單號
	RecordId             int64    `protobuf:"varint,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordGetQRCodeReq) Reset()         { *m = RecordGetQRCodeReq{} }
func (m *RecordGetQRCodeReq) String() string { return proto.CompactTextString(m) }
func (*RecordGetQRCodeReq) ProtoMessage()    {}
func (*RecordGetQRCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{6}
}

func (m *RecordGetQRCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordGetQRCodeReq.Unmarshal(m, b)
}
func (m *RecordGetQRCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordGetQRCodeReq.Marshal(b, m, deterministic)
}
func (m *RecordGetQRCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordGetQRCodeReq.Merge(m, src)
}
func (m *RecordGetQRCodeReq) XXX_Size() int {
	return xxx_messageInfo_RecordGetQRCodeReq.Size(m)
}
func (m *RecordGetQRCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordGetQRCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordGetQRCodeReq proto.InternalMessageInfo

func (m *RecordGetQRCodeReq) GetRecordId() int64 {
	if m != nil {
		return m.RecordId
	}
	return 0
}

type RecordGetQRCodeResp struct {
	// QR Code
	QrCode               string   `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordGetQRCodeResp) Reset()         { *m = RecordGetQRCodeResp{} }
func (m *RecordGetQRCodeResp) String() string { return proto.CompactTextString(m) }
func (*RecordGetQRCodeResp) ProtoMessage()    {}
func (*RecordGetQRCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{7}
}

func (m *RecordGetQRCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordGetQRCodeResp.Unmarshal(m, b)
}
func (m *RecordGetQRCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordGetQRCodeResp.Marshal(b, m, deterministic)
}
func (m *RecordGetQRCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordGetQRCodeResp.Merge(m, src)
}
func (m *RecordGetQRCodeResp) XXX_Size() int {
	return xxx_messageInfo_RecordGetQRCodeResp.Size(m)
}
func (m *RecordGetQRCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordGetQRCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordGetQRCodeResp proto.InternalMessageInfo

func (m *RecordGetQRCodeResp) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

// 同步搶單種類及明細
type RecordSyncPaymentReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordSyncPaymentReq) Reset()         { *m = RecordSyncPaymentReq{} }
func (m *RecordSyncPaymentReq) String() string { return proto.CompactTextString(m) }
func (*RecordSyncPaymentReq) ProtoMessage()    {}
func (*RecordSyncPaymentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{8}
}

func (m *RecordSyncPaymentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSyncPaymentReq.Unmarshal(m, b)
}
func (m *RecordSyncPaymentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSyncPaymentReq.Marshal(b, m, deterministic)
}
func (m *RecordSyncPaymentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSyncPaymentReq.Merge(m, src)
}
func (m *RecordSyncPaymentReq) XXX_Size() int {
	return xxx_messageInfo_RecordSyncPaymentReq.Size(m)
}
func (m *RecordSyncPaymentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSyncPaymentReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSyncPaymentReq proto.InternalMessageInfo

type RecordSyncPaymentResp struct {
	// 類型
	Payment []*RecordSyncPayment `protobuf:"bytes,1,rep,name=payment,proto3" json:"payment,omitempty"`
	// 類型明細
	PaymentDtl           []*RecordSyncPaymentDtl `protobuf:"bytes,2,rep,name=payment_dtl,json=paymentDtl,proto3" json:"payment_dtl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RecordSyncPaymentResp) Reset()         { *m = RecordSyncPaymentResp{} }
func (m *RecordSyncPaymentResp) String() string { return proto.CompactTextString(m) }
func (*RecordSyncPaymentResp) ProtoMessage()    {}
func (*RecordSyncPaymentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{9}
}

func (m *RecordSyncPaymentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSyncPaymentResp.Unmarshal(m, b)
}
func (m *RecordSyncPaymentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSyncPaymentResp.Marshal(b, m, deterministic)
}
func (m *RecordSyncPaymentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSyncPaymentResp.Merge(m, src)
}
func (m *RecordSyncPaymentResp) XXX_Size() int {
	return xxx_messageInfo_RecordSyncPaymentResp.Size(m)
}
func (m *RecordSyncPaymentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSyncPaymentResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSyncPaymentResp proto.InternalMessageInfo

func (m *RecordSyncPaymentResp) GetPayment() []*RecordSyncPayment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *RecordSyncPaymentResp) GetPaymentDtl() []*RecordSyncPaymentDtl {
	if m != nil {
		return m.PaymentDtl
	}
	return nil
}

type RecordSyncPayment struct {
	// 類型 id
	PaymentId int64 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// 名稱
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordSyncPayment) Reset()         { *m = RecordSyncPayment{} }
func (m *RecordSyncPayment) String() string { return proto.CompactTextString(m) }
func (*RecordSyncPayment) ProtoMessage()    {}
func (*RecordSyncPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{10}
}

func (m *RecordSyncPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSyncPayment.Unmarshal(m, b)
}
func (m *RecordSyncPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSyncPayment.Marshal(b, m, deterministic)
}
func (m *RecordSyncPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSyncPayment.Merge(m, src)
}
func (m *RecordSyncPayment) XXX_Size() int {
	return xxx_messageInfo_RecordSyncPayment.Size(m)
}
func (m *RecordSyncPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSyncPayment.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSyncPayment proto.InternalMessageInfo

func (m *RecordSyncPayment) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *RecordSyncPayment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RecordSyncPaymentDtl struct {
	// 類型明細 id
	PaymentDtlId int64 `protobuf:"varint,1,opt,name=payment_dtl_id,json=paymentDtlId,proto3" json:"payment_dtl_id,omitempty"`
	// 類型 id
	PaymentId int64 `protobuf:"varint,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	// 金額
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordSyncPaymentDtl) Reset()         { *m = RecordSyncPaymentDtl{} }
func (m *RecordSyncPaymentDtl) String() string { return proto.CompactTextString(m) }
func (*RecordSyncPaymentDtl) ProtoMessage()    {}
func (*RecordSyncPaymentDtl) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{11}
}

func (m *RecordSyncPaymentDtl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordSyncPaymentDtl.Unmarshal(m, b)
}
func (m *RecordSyncPaymentDtl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordSyncPaymentDtl.Marshal(b, m, deterministic)
}
func (m *RecordSyncPaymentDtl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordSyncPaymentDtl.Merge(m, src)
}
func (m *RecordSyncPaymentDtl) XXX_Size() int {
	return xxx_messageInfo_RecordSyncPaymentDtl.Size(m)
}
func (m *RecordSyncPaymentDtl) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordSyncPaymentDtl.DiscardUnknown(m)
}

var xxx_messageInfo_RecordSyncPaymentDtl proto.InternalMessageInfo

func (m *RecordSyncPaymentDtl) GetPaymentDtlId() int64 {
	if m != nil {
		return m.PaymentDtlId
	}
	return 0
}

func (m *RecordSyncPaymentDtl) GetPaymentId() int64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *RecordSyncPaymentDtl) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// 撮合成功通知
type RecordNotifyHitReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordNotifyHitReq) Reset()         { *m = RecordNotifyHitReq{} }
func (m *RecordNotifyHitReq) String() string { return proto.CompactTextString(m) }
func (*RecordNotifyHitReq) ProtoMessage()    {}
func (*RecordNotifyHitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{12}
}

func (m *RecordNotifyHitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordNotifyHitReq.Unmarshal(m, b)
}
func (m *RecordNotifyHitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordNotifyHitReq.Marshal(b, m, deterministic)
}
func (m *RecordNotifyHitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordNotifyHitReq.Merge(m, src)
}
func (m *RecordNotifyHitReq) XXX_Size() int {
	return xxx_messageInfo_RecordNotifyHitReq.Size(m)
}
func (m *RecordNotifyHitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordNotifyHitReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordNotifyHitReq proto.InternalMessageInfo

type RecordNotifyHitResp struct {
	// 期數id
	RecordId string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// QR Code
	QrCode               string   `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordNotifyHitResp) Reset()         { *m = RecordNotifyHitResp{} }
func (m *RecordNotifyHitResp) String() string { return proto.CompactTextString(m) }
func (*RecordNotifyHitResp) ProtoMessage()    {}
func (*RecordNotifyHitResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{13}
}

func (m *RecordNotifyHitResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordNotifyHitResp.Unmarshal(m, b)
}
func (m *RecordNotifyHitResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordNotifyHitResp.Marshal(b, m, deterministic)
}
func (m *RecordNotifyHitResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordNotifyHitResp.Merge(m, src)
}
func (m *RecordNotifyHitResp) XXX_Size() int {
	return xxx_messageInfo_RecordNotifyHitResp.Size(m)
}
func (m *RecordNotifyHitResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordNotifyHitResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordNotifyHitResp proto.InternalMessageInfo

func (m *RecordNotifyHitResp) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func (m *RecordNotifyHitResp) GetQrCode() string {
	if m != nil {
		return m.QrCode
	}
	return ""
}

// 到款確認通知
type RecordNotifyConfirmReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordNotifyConfirmReq) Reset()         { *m = RecordNotifyConfirmReq{} }
func (m *RecordNotifyConfirmReq) String() string { return proto.CompactTextString(m) }
func (*RecordNotifyConfirmReq) ProtoMessage()    {}
func (*RecordNotifyConfirmReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{14}
}

func (m *RecordNotifyConfirmReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordNotifyConfirmReq.Unmarshal(m, b)
}
func (m *RecordNotifyConfirmReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordNotifyConfirmReq.Marshal(b, m, deterministic)
}
func (m *RecordNotifyConfirmReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordNotifyConfirmReq.Merge(m, src)
}
func (m *RecordNotifyConfirmReq) XXX_Size() int {
	return xxx_messageInfo_RecordNotifyConfirmReq.Size(m)
}
func (m *RecordNotifyConfirmReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordNotifyConfirmReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecordNotifyConfirmReq proto.InternalMessageInfo

type RecordNotifyConfirmResp struct {
	// 期數id
	RecordId             string   `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordNotifyConfirmResp) Reset()         { *m = RecordNotifyConfirmResp{} }
func (m *RecordNotifyConfirmResp) String() string { return proto.CompactTextString(m) }
func (*RecordNotifyConfirmResp) ProtoMessage()    {}
func (*RecordNotifyConfirmResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf94fd919e302a1d, []int{15}
}

func (m *RecordNotifyConfirmResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordNotifyConfirmResp.Unmarshal(m, b)
}
func (m *RecordNotifyConfirmResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordNotifyConfirmResp.Marshal(b, m, deterministic)
}
func (m *RecordNotifyConfirmResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordNotifyConfirmResp.Merge(m, src)
}
func (m *RecordNotifyConfirmResp) XXX_Size() int {
	return xxx_messageInfo_RecordNotifyConfirmResp.Size(m)
}
func (m *RecordNotifyConfirmResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordNotifyConfirmResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecordNotifyConfirmResp proto.InternalMessageInfo

func (m *RecordNotifyConfirmResp) GetRecordId() string {
	if m != nil {
		return m.RecordId
	}
	return ""
}

func init() {
	proto.RegisterEnum("zqbrecord.RecordAddStatus_Enum", RecordAddStatus_Enum_name, RecordAddStatus_Enum_value)
	proto.RegisterEnum("zqbrecord.OrderRevenueStatus_Enum", OrderRevenueStatus_Enum_name, OrderRevenueStatus_Enum_value)
	proto.RegisterType((*RecordAddStatus)(nil), "zqbrecord.RecordAddStatus")
	proto.RegisterType((*RecordAddReq)(nil), "zqbrecord.RecordAddReq")
	proto.RegisterType((*RecordAddResp)(nil), "zqbrecord.RecordAddResp")
	proto.RegisterType((*OrderRevenueStatus)(nil), "zqbrecord.OrderRevenueStatus")
	proto.RegisterType((*RecordGetStatusReq)(nil), "zqbrecord.RecordGetStatusReq")
	proto.RegisterType((*RecordGetStatusResp)(nil), "zqbrecord.RecordGetStatusResp")
	proto.RegisterType((*RecordGetQRCodeReq)(nil), "zqbrecord.RecordGetQRCodeReq")
	proto.RegisterType((*RecordGetQRCodeResp)(nil), "zqbrecord.RecordGetQRCodeResp")
	proto.RegisterType((*RecordSyncPaymentReq)(nil), "zqbrecord.RecordSyncPaymentReq")
	proto.RegisterType((*RecordSyncPaymentResp)(nil), "zqbrecord.RecordSyncPaymentResp")
	proto.RegisterType((*RecordSyncPayment)(nil), "zqbrecord.RecordSyncPayment")
	proto.RegisterType((*RecordSyncPaymentDtl)(nil), "zqbrecord.RecordSyncPaymentDtl")
	proto.RegisterType((*RecordNotifyHitReq)(nil), "zqbrecord.RecordNotifyHitReq")
	proto.RegisterType((*RecordNotifyHitResp)(nil), "zqbrecord.RecordNotifyHitResp")
	proto.RegisterType((*RecordNotifyConfirmReq)(nil), "zqbrecord.RecordNotifyConfirmReq")
	proto.RegisterType((*RecordNotifyConfirmResp)(nil), "zqbrecord.RecordNotifyConfirmResp")
}

func init() {
	proto.RegisterFile("record.proto", fileDescriptor_bf94fd919e302a1d)
}

var fileDescriptor_bf94fd919e302a1d = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x5d, 0x6f, 0x12, 0x5d,
	0x10, 0x7e, 0x97, 0x25, 0x4b, 0x77, 0xa0, 0x7d, 0xe9, 0x58, 0x61, 0x83, 0xd6, 0xae, 0x27, 0x5e,
	0x70, 0x45, 0x94, 0x9a, 0x6a, 0xbc, 0xb2, 0x29, 0x7e, 0xa0, 0x46, 0xeb, 0xe9, 0x8d, 0x77, 0x64,
	0xcb, 0x39, 0xa4, 0x9b, 0xc0, 0x7e, 0x9d, 0xb3, 0x26, 0xf8, 0x2f, 0xfc, 0x6f, 0xfe, 0x1f, 0xcd,
	0x7e, 0x72, 0x80, 0x15, 0xe4, 0x6a, 0xcf, 0xcc, 0x3c, 0x33, 0xcf, 0xcc, 0x33, 0x13, 0xa0, 0x15,
	0xf1, 0xa9, 0x1f, 0xb1, 0x41, 0x10, 0xf9, 0xd2, 0x47, 0xf3, 0x47, 0x78, 0x9b, 0x19, 0xc8, 0x39,
	0xfc, 0x4f, 0xd3, 0xaf, 0x4b, 0xc6, 0x6e, 0xa4, 0x23, 0x63, 0x41, 0x6c, 0xa8, 0xbf, 0xf1, 0xe2,
	0x05, 0x36, 0xa1, 0x31, 0x73, 0xdc, 0x79, 0x1c, 0xf1, 0xf6, 0x7f, 0xc9, 0x43, 0xc4, 0xd3, 0x29,
	0x17, 0xa2, 0xad, 0x91, 0xe7, 0xd0, 0x2a, 0x41, 0x94, 0x87, 0xf8, 0x04, 0x8e, 0x02, 0x67, 0xb9,
	0xe0, 0x9e, 0x9c, 0x30, 0x39, 0x9f, 0xb8, 0xcc, 0xd2, 0x6c, 0xad, 0xaf, 0xd3, 0x56, 0x6e, 0x1d,
	0xc9, 0xf9, 0x98, 0x11, 0x0e, 0x87, 0x0a, 0x4a, 0x04, 0xf8, 0x00, 0xcc, 0x8c, 0xc5, 0x0a, 0x71,
	0x90, 0x19, 0xc6, 0x0c, 0x5f, 0x80, 0x21, 0x52, 0x3e, 0x56, 0xcd, 0xd6, 0xfa, 0x47, 0xc3, 0xb3,
	0x41, 0x49, 0x7a, 0xb0, 0xc1, 0x78, 0x90, 0xd0, 0xa5, 0x79, 0x38, 0xb9, 0x03, 0xfc, 0x12, 0x31,
	0x1e, 0x51, 0xfe, 0x9d, 0x7b, 0x31, 0xcf, 0x9b, 0xa2, 0x79, 0x53, 0x07, 0x50, 0x0f, 0x1c, 0x37,
	0xda, 0xe8, 0x48, 0xed, 0xb5, 0x86, 0x0d, 0xd0, 0xef, 0x5c, 0xd9, 0xd6, 0x11, 0xc0, 0x88, 0xbd,
	0xc0, 0x71, 0x59, 0xbb, 0x8e, 0xc7, 0x50, 0xf7, 0x7c, 0x8f, 0xb7, 0x7f, 0x17, 0x3f, 0x8d, 0x3c,
	0x03, 0xcc, 0x98, 0xbc, 0xe3, 0x32, 0x2b, 0x93, 0x0c, 0x63, 0x57, 0x57, 0xc4, 0x83, 0x7b, 0x5b,
	0x90, 0x7d, 0x93, 0x78, 0xb5, 0x31, 0x09, 0xa2, 0x4c, 0x62, 0xbb, 0xd3, 0xf5, 0x61, 0xa8, 0x14,
	0xbf, 0xd2, 0x2b, 0x9f, 0xf1, 0xbd, 0x14, 0x07, 0x0a, 0xc5, 0x02, 0x22, 0x02, 0xec, 0x42, 0x23,
	0x8c, 0x26, 0x53, 0x9f, 0xf1, 0x14, 0x61, 0x52, 0x23, 0x8c, 0x12, 0x27, 0xe9, 0xc0, 0x49, 0x16,
	0x7f, 0xb3, 0xf4, 0xa6, 0xd7, 0x99, 0xe0, 0x94, 0x87, 0xe4, 0xa7, 0x06, 0xf7, 0x2b, 0x1c, 0x22,
	0xc0, 0x0b, 0x68, 0xe4, 0x8b, 0x61, 0x69, 0xb6, 0xde, 0x6f, 0x0e, 0x1f, 0x6e, 0x69, 0xab, 0x42,
	0x8a, 0x60, 0x7c, 0x0d, 0x4d, 0x65, 0xcd, 0xac, 0x5a, 0x8a, 0x3d, 0xdb, 0x85, 0x1d, 0xc9, 0x39,
	0x85, 0xd5, 0x12, 0x92, 0xb7, 0x70, 0xbc, 0x15, 0x83, 0xa7, 0x50, 0x84, 0xac, 0xc6, 0x61, 0xe6,
	0x96, 0x31, 0x43, 0x84, 0xba, 0xe7, 0x2c, 0x78, 0x3a, 0x7c, 0x93, 0xa6, 0xdf, 0x44, 0x54, 0xf4,
	0x3c, 0x92, 0xf3, 0x7f, 0x3b, 0x84, 0x8d, 0x82, 0xb5, 0xcd, 0x82, 0x1d, 0x30, 0x9c, 0x85, 0x1f,
	0x7b, 0xd2, 0xd2, 0x6d, 0xad, 0xaf, 0xd1, 0xfc, 0x45, 0x4e, 0x0a, 0x2d, 0x3f, 0xfb, 0xd2, 0x9d,
	0x2d, 0xdf, 0xbb, 0xe9, 0x98, 0x3f, 0x16, 0x72, 0x29, 0xd6, 0xaa, 0x8d, 0x32, 0x95, 0x8d, 0x52,
	0xb4, 0xac, 0xad, 0x69, 0x69, 0x41, 0x47, 0x4d, 0x76, 0xe5, 0x7b, 0x33, 0x37, 0x5a, 0x24, 0x65,
	0x2e, 0xa0, 0x5b, 0xe9, 0xd9, 0x53, 0x6a, 0xf8, 0x4b, 0x07, 0x23, 0x03, 0xe2, 0x4b, 0xd0, 0x2f,
	0x19, 0xc3, 0x6e, 0xd5, 0x21, 0x53, 0x1e, 0xf6, 0xac, 0x6a, 0x87, 0x08, 0xf0, 0x03, 0x98, 0xe5,
	0xbd, 0xe0, 0xe9, 0x56, 0x98, 0x7a, 0x7e, 0xbd, 0x47, 0xbb, 0xdc, 0x65, 0xae, 0x6c, 0xb1, 0xab,
	0x73, 0x95, 0x77, 0x52, 0x9d, 0x4b, 0xb9, 0x89, 0x6b, 0x68, 0xaa, 0x8b, 0xb4, 0x73, 0x15, 0x93,
	0x7c, 0xf6, 0xee, 0x00, 0x11, 0xe0, 0x27, 0x30, 0x4b, 0x1d, 0x2b, 0xd8, 0xa9, 0xca, 0x57, 0xb0,
	0x5b, 0x5b, 0x81, 0xa7, 0x1a, 0x7e, 0x83, 0xc3, 0x35, 0xb9, 0xf0, 0xf1, 0x5f, 0x20, 0x2b, 0xa1,
	0x7b, 0x64, 0x5f, 0x48, 0x92, 0xf9, 0xd6, 0x48, 0xff, 0x48, 0xce, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x76, 0xce, 0x26, 0xfc, 0x58, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecordClient is the client API for Record service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordClient interface {
	// 收單
	Add(ctx context.Context, in *RecordAddReq, opts ...grpc.CallOption) (*RecordAddResp, error)
	// 狀態查詢
	GetStatus(ctx context.Context, in *RecordGetStatusReq, opts ...grpc.CallOption) (*RecordGetStatusResp, error)
	// 取得QRCode
	GetQRCode(ctx context.Context, in *RecordGetQRCodeReq, opts ...grpc.CallOption) (*RecordGetQRCodeResp, error)
	// 同步搶單種類及明細
	SyncPayment(ctx context.Context, in *RecordSyncPaymentReq, opts ...grpc.CallOption) (*RecordSyncPaymentResp, error)
	// 撮合成功通知
	NotifyHit(ctx context.Context, in *RecordNotifyHitReq, opts ...grpc.CallOption) (Record_NotifyHitClient, error)
	// 到款確認通知
	NotifyConfirm(ctx context.Context, in *RecordNotifyConfirmReq, opts ...grpc.CallOption) (Record_NotifyConfirmClient, error)
}

type recordClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordClient(cc grpc.ClientConnInterface) RecordClient {
	return &recordClient{cc}
}

func (c *recordClient) Add(ctx context.Context, in *RecordAddReq, opts ...grpc.CallOption) (*RecordAddResp, error) {
	out := new(RecordAddResp)
	err := c.cc.Invoke(ctx, "/zqbrecord.Record/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) GetStatus(ctx context.Context, in *RecordGetStatusReq, opts ...grpc.CallOption) (*RecordGetStatusResp, error) {
	out := new(RecordGetStatusResp)
	err := c.cc.Invoke(ctx, "/zqbrecord.Record/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) GetQRCode(ctx context.Context, in *RecordGetQRCodeReq, opts ...grpc.CallOption) (*RecordGetQRCodeResp, error) {
	out := new(RecordGetQRCodeResp)
	err := c.cc.Invoke(ctx, "/zqbrecord.Record/GetQRCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) SyncPayment(ctx context.Context, in *RecordSyncPaymentReq, opts ...grpc.CallOption) (*RecordSyncPaymentResp, error) {
	out := new(RecordSyncPaymentResp)
	err := c.cc.Invoke(ctx, "/zqbrecord.Record/SyncPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordClient) NotifyHit(ctx context.Context, in *RecordNotifyHitReq, opts ...grpc.CallOption) (Record_NotifyHitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Record_serviceDesc.Streams[0], "/zqbrecord.Record/NotifyHit", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordNotifyHitClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Record_NotifyHitClient interface {
	Recv() (*RecordNotifyHitResp, error)
	grpc.ClientStream
}

type recordNotifyHitClient struct {
	grpc.ClientStream
}

func (x *recordNotifyHitClient) Recv() (*RecordNotifyHitResp, error) {
	m := new(RecordNotifyHitResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recordClient) NotifyConfirm(ctx context.Context, in *RecordNotifyConfirmReq, opts ...grpc.CallOption) (Record_NotifyConfirmClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Record_serviceDesc.Streams[1], "/zqbrecord.Record/NotifyConfirm", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordNotifyConfirmClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Record_NotifyConfirmClient interface {
	Recv() (*RecordNotifyConfirmResp, error)
	grpc.ClientStream
}

type recordNotifyConfirmClient struct {
	grpc.ClientStream
}

func (x *recordNotifyConfirmClient) Recv() (*RecordNotifyConfirmResp, error) {
	m := new(RecordNotifyConfirmResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecordServer is the server API for Record service.
type RecordServer interface {
	// 收單
	Add(context.Context, *RecordAddReq) (*RecordAddResp, error)
	// 狀態查詢
	GetStatus(context.Context, *RecordGetStatusReq) (*RecordGetStatusResp, error)
	// 取得QRCode
	GetQRCode(context.Context, *RecordGetQRCodeReq) (*RecordGetQRCodeResp, error)
	// 同步搶單種類及明細
	SyncPayment(context.Context, *RecordSyncPaymentReq) (*RecordSyncPaymentResp, error)
	// 撮合成功通知
	NotifyHit(*RecordNotifyHitReq, Record_NotifyHitServer) error
	// 到款確認通知
	NotifyConfirm(*RecordNotifyConfirmReq, Record_NotifyConfirmServer) error
}

// UnimplementedRecordServer can be embedded to have forward compatible implementations.
type UnimplementedRecordServer struct {
}

func (*UnimplementedRecordServer) Add(ctx context.Context, req *RecordAddReq) (*RecordAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedRecordServer) GetStatus(ctx context.Context, req *RecordGetStatusReq) (*RecordGetStatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (*UnimplementedRecordServer) GetQRCode(ctx context.Context, req *RecordGetQRCodeReq) (*RecordGetQRCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRCode not implemented")
}
func (*UnimplementedRecordServer) SyncPayment(ctx context.Context, req *RecordSyncPaymentReq) (*RecordSyncPaymentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncPayment not implemented")
}
func (*UnimplementedRecordServer) NotifyHit(req *RecordNotifyHitReq, srv Record_NotifyHitServer) error {
	return status.Errorf(codes.Unimplemented, "method NotifyHit not implemented")
}
func (*UnimplementedRecordServer) NotifyConfirm(req *RecordNotifyConfirmReq, srv Record_NotifyConfirmServer) error {
	return status.Errorf(codes.Unimplemented, "method NotifyConfirm not implemented")
}

func RegisterRecordServer(s *grpc.Server, srv RecordServer) {
	s.RegisterService(&_Record_serviceDesc, srv)
}

func _Record_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zqbrecord.Record/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).Add(ctx, req.(*RecordAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordGetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zqbrecord.Record/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).GetStatus(ctx, req.(*RecordGetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordGetQRCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zqbrecord.Record/GetQRCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).GetQRCode(ctx, req.(*RecordGetQRCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_SyncPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSyncPaymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).SyncPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zqbrecord.Record/SyncPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).SyncPayment(ctx, req.(*RecordSyncPaymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Record_NotifyHit_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecordNotifyHitReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordServer).NotifyHit(m, &recordNotifyHitServer{stream})
}

type Record_NotifyHitServer interface {
	Send(*RecordNotifyHitResp) error
	grpc.ServerStream
}

type recordNotifyHitServer struct {
	grpc.ServerStream
}

func (x *recordNotifyHitServer) Send(m *RecordNotifyHitResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Record_NotifyConfirm_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecordNotifyConfirmReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordServer).NotifyConfirm(m, &recordNotifyConfirmServer{stream})
}

type Record_NotifyConfirmServer interface {
	Send(*RecordNotifyConfirmResp) error
	grpc.ServerStream
}

type recordNotifyConfirmServer struct {
	grpc.ServerStream
}

func (x *recordNotifyConfirmServer) Send(m *RecordNotifyConfirmResp) error {
	return x.ServerStream.SendMsg(m)
}

var _Record_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zqbrecord.Record",
	HandlerType: (*RecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Record_Add_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Record_GetStatus_Handler,
		},
		{
			MethodName: "GetQRCode",
			Handler:    _Record_GetQRCode_Handler,
		},
		{
			MethodName: "SyncPayment",
			Handler:    _Record_SyncPayment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "NotifyHit",
			Handler:       _Record_NotifyHit_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NotifyConfirm",
			Handler:       _Record_NotifyConfirm_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "record.proto",
}
